# Generated by Django 5.1.5 on 2025-01-29 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
        migrations.RemoveField(
            model_name='county',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='county',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.county'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='county',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='core.province'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(default='9297460036', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='2712049496', max_length=10, unique=True),
        ),
    ]
