# Generated by Django 5.1.5 on 2025-01-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_poi_weekday_city_lat_city_lng_openinghour'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
        migrations.AlterModelTable(
            name='province',
            table='province',
        ),
    ]
