# Generated by Django 5.1.5 on 2025-01-29 09:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_city_province_remove_county_city_city_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='county',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(default='7441281519', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='4121141180', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
