# Generated by Django 5.1.5 on 2025-01-29 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_city_coordinates_alter_county_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='core.province'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(default='6096642552', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='8996233335', max_length=10, unique=True),
        ),
    ]
