# Generated by Django 5.1.5 on 2025-01-21 20:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_city_table_alter_province_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saturday', models.TimeField()),
                ('sunday', models.TimeField()),
                ('monday', models.TimeField()),
                ('tuesday', models.TimeField()),
                ('wednesday', models.TimeField()),
                ('thursday', models.TimeField()),
                ('friday', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JobLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('robika', models.URLField(blank=True, null=True)),
                ('eitaa', models.URLField(blank=True, null=True)),
                ('bale', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
            ],
        ),
        migrations.RemoveField(
            model_name='openinghour',
            name='weekday',
        ),
        migrations.DeleteModel(
            name='POI',
        ),
        migrations.AddField(
            model_name='job',
            name='is_producer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='job_code',
            field=models.CharField(default='2183022265', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='purchase_in_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='purchase_in_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='city_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_mobile_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='province_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='remember_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='2942561547', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='jobhours',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job'),
        ),
        migrations.AddField(
            model_name='joblinks',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job'),
        ),
        migrations.DeleteModel(
            name='OpeningHour',
        ),
        migrations.DeleteModel(
            name='Weekday',
        ),
    ]
