# Generated by Django 5.1.5 on 2025-01-29 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_village_province_alter_job_job_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='city',
        ),
        migrations.AddField(
            model_name='district',
            name='county',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.county', verbose_name='شهرستان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(default='9099888503', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='9849709323', max_length=10, unique=True),
        ),
    ]
