# Generated by Django 5.1.5 on 2025-01-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_district_city_district_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='county_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(default='8635939574', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='3233473049', max_length=10, unique=True),
        ),
    ]
