# Generated by Django 5.1.5 on 2025-02-02 17:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_county_id_alter_job_job_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='user',
            name='village_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(default='3349954869', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='7459276062', max_length=10, unique=True),
        ),
    ]
