# Generated by Django 5.1.5 on 2025-02-04 10:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_coordinates_user_village_id_alter_job_job_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobhours',
            options={'verbose_name': 'ساعت کاری', 'verbose_name_plural': 'ساعت\u200cهای کاری'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='job',
            name='lng',
        ),
        migrations.AddField(
            model_name='jobhours',
            name='day',
            field=models.CharField(choices=[('sat', 'شنبه'), ('sun', 'یکشنبه'), ('mon', 'دوشنبه'), ('tue', 'سه\u200cشنبه'), ('wed', 'چهارشنبه'), ('thu', 'پنجشنبه'), ('fri', 'جمعه')], default=1, max_length=3, verbose_name='روز هفته'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobhours',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='تعطیل'),
        ),
        migrations.AlterUniqueTogether(
            name='jobhours',
            unique_together={('job', 'day')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lng',
        ),
        migrations.AddField(
            model_name='job',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='مختصات'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(default='2148934638', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='jobhours',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job', verbose_name='کسب\u200cوکار'),
        ),
        migrations.AlterField(
            model_name='user',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='مختصات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='1202633526', max_length=10, unique=True),
        ),
        migrations.AlterModelTable(
            name='joblinks',
            table='job_links',
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('job_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='core.jobhours', verbose_name='ساعت کاری')),
            ],
            options={
                'verbose_name': 'بازه زمانی',
                'verbose_name_plural': 'بازه\u200cهای زمانی',
                'db_table': 'time_slots',
            },
        ),
        migrations.RemoveField(
            model_name='jobhours',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='jobhours',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='jobhours',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='jobhours',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='jobhours',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='jobhours',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='jobhours',
            name='wednesday',
        ),
    ]