# Generated by Django 5.1.5 on 2025-01-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_created_by_admin_alter_job_job_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(default='9742474435', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='3635292594', max_length=10, unique=True),
        ),
    ]
