# Generated by Django 5.1.5 on 2025-02-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_jobhours_options_remove_job_lat_remove_job_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(default='1498680611', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_mobile_confirmed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='4263017869', max_length=10, unique=True),
        ),
    ]
