# Generated by Django 5.1.5 on 2025-01-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_lat_user_lng_alter_job_job_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(default='1003412488', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='6000113758', max_length=10, unique=True),
        ),
    ]
