# Generated by Django 5.1.5 on 2025-02-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_job_job_code_alter_user_is_mobile_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(default='7949611009', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='5129508950', max_length=10, unique=True),
        ),
    ]
