# Generated by Django 5.1.5 on 2025-02-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_job_job_code_alter_user_user_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_job',
            options={'get_latest_by': 'updated_at', 'ordering': ['sort_order'], 'verbose_name': 'دسته\u200cبندی مشاغل', 'verbose_name_plural': 'دسته\u200cبندی مشاغل'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name'], 'verbose_name': 'منطقه', 'verbose_name_plural': 'مناطق'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at'], 'verbose_name': 'کار', 'verbose_name_plural': 'کارها'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'نقش', 'verbose_name_plural': 'نقش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(default='8547503048', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='7585802187', max_length=10, unique=True),
        ),
    ]
