# Generated by Django 5.1.5 on 2025-01-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_job_job_code_alter_user_lat_alter_user_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(default='3476655965', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='3019522643', max_length=10, unique=True),
        ),
    ]
