# Generated by Django 5.1.5 on 2025-02-10 19:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_category_job_options_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(default=core.models.generate_job_code, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='6176212095', max_length=10, unique=True),
        ),
    ]
