# Generated by Django 5.1.5 on 2025-02-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_job_job_code_alter_user_user_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joblinks',
            options={'verbose_name': 'لینک شغل ', 'verbose_name_plural': 'لینک های شغل'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='3800994215', max_length=10, unique=True),
        ),
    ]
