# Generated by Django 5.1.5 on 2025-01-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_job_job_code_alter_user_lat_alter_user_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(default='8639632657', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='8312103755', max_length=10, unique=True),
        ),
    ]
