# Generated by Django 5.1.5 on 2025-02-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_joblinks_options_alter_user_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='8337377268', max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('job_hour', 'start_time', 'end_time'), name='unique_time_slot'),
        ),
    ]
