# Generated by Django 5.1.5 on 2025-01-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_job_job_code_alter_user_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(default='7030909962', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='3681023847', max_length=10, unique=True),
        ),
    ]
