# Generated by Django 5.1.5 on 2025-02-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_job_region_remove_user_region_job_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.AddField(
            model_name='user',
            name='district_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='2416661017', max_length=10, unique=True),
        ),
    ]
