# Generated by Django 5.1.5 on 2025-03-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_user_user_code_place_job_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.village'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='2815219153', max_length=10, unique=True),
        ),
    ]
