# Generated by Django 5.1.5 on 2025-03-05 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_user_user_code_category_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.county'),
        ),
        migrations.AddField(
            model_name='place',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.county'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='8324203698', max_length=10, unique=True),
        ),
        migrations.AlterModelTable(
            name='category_place',
            table='category_place',
        ),
    ]
