# Generated by Django 5.1.5 on 2025-03-05 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_job_county_place_county_alter_user_user_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='core.city'),
        ),
        migrations.AlterField(
            model_name='place',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='core.county'),
        ),
        migrations.AlterField(
            model_name='place',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='core.district'),
        ),
        migrations.AlterField(
            model_name='place',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='core.province'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='2420140323', max_length=10, unique=True),
        ),
    ]
