# Generated by Django 5.1.5 on 2025-03-06 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_place_city_alter_place_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city'),
        ),
        migrations.AlterField(
            model_name='job',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.county'),
        ),
        migrations.AlterField(
            model_name='job',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.district'),
        ),
        migrations.AlterField(
            model_name='job',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.province'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.CharField(default='3590240488', max_length=10, unique=True),
        ),
    ]
